apiVersion: v1
kind: Namespace
metadata:
  name: $NS
  labels:
    kubernetes.io/namespace: $NS
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: $NS
  namespace: $NS
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 6Gi
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: $NS
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allowtraffic-namespace
  namespace: $NS
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/namespace: $NS
  podSelector: {}
  policyTypes:
  - Ingress
